# 消融实验配置：大规模 MoE
# 更多专家，更高激活数

model:
  in_channels: 3
  model_channels: 128
  channel_mults: [1, 2, 4, 8]
  t_dim: 512
  c_dim: 512

moe:
  enabled: true
  num_experts: 16             # 增加专家数量
  k_active: 4                 # 增加激活数量

freq:
  enabled: true

train:
  lambda_load: 0.01
  learning_rate: 1.0e-4
  weight_decay: 0.0
  batch_size: 16
  num_epochs: 100
  use_dsconv_global: true
  image_size: 64
  num_classes: 10
  log_interval: 100
  save_interval: 1000
  checkpoint_dir: "./checkpoints_large_moe"

diffusion:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  schedule: "linear"

