# 消融实验配置：最小基线
# 禁用所有创新组件

model:
  in_channels: 3
  model_channels: 128
  channel_mults: [1, 2, 4, 8]
  t_dim: 512
  c_dim: 512

moe:
  enabled: false              # 禁用 MoE
  num_experts: 8
  k_active: 2

freq:
  enabled: false              # 禁用频率域模块

train:
  lambda_load: 0.01
  learning_rate: 1.0e-4
  weight_decay: 0.0
  batch_size: 16
  num_epochs: 100
  use_dsconv_global: false    # 禁用 DS-Conv
  image_size: 64
  num_classes: 10
  log_interval: 100
  save_interval: 1000
  checkpoint_dir: "./checkpoints_minimal"

diffusion:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  schedule: "linear"

