# SR 配置：2倍超分辨率

model:
  in_channels: 3
  model_channels: 128
  channel_mults: [1, 2, 4, 8]
  t_dim: 512
  c_dim: 512

moe:
  enabled: true
  num_experts: 8
  k_active: 2

freq:
  enabled: true

sr:
  scale_factor: 2             # 2倍超分
  lr_channels: 64

train:
  lambda_load: 0.01
  learning_rate: 2.0e-4
  weight_decay: 0.0
  batch_size: 16              # 2x 可以用更大的批次
  num_epochs: 200
  use_dsconv_global: true
  hr_size: 256
  lr_size: 128                # 2x: 256/2 = 128
  num_classes: 10
  log_interval: 50
  save_interval: 1000
  checkpoint_dir: "./checkpoints_sr_2x"
  val_interval: 500
  num_val_images: 8

diffusion:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  schedule: "linear"
  sampling_timesteps: 250
  ddim_eta: 0.0

augmentation:
  random_flip: true
  random_crop: true
  color_jitter: false

