# SR 配置：8倍超分辨率（挑战性任务）

model:
  in_channels: 3
  model_channels: 128
  channel_mults: [1, 2, 4, 8]
  t_dim: 512
  c_dim: 512

moe:
  enabled: true
  num_experts: 16             # 8x 需要更多专家
  k_active: 4                 # 更多激活专家

freq:
  enabled: true

sr:
  scale_factor: 8             # 8倍超分
  lr_channels: 128            # 更多 LR 特征通道

train:
  lambda_load: 0.01
  learning_rate: 1.5e-4       # 略低的学习率
  weight_decay: 0.0
  batch_size: 4               # 8x 显存消耗大
  num_epochs: 300             # 更多训练轮数
  use_dsconv_global: true
  hr_size: 256
  lr_size: 32                 # 8x: 256/8 = 32
  num_classes: 10
  log_interval: 50
  save_interval: 1000
  checkpoint_dir: "./checkpoints_sr_8x"
  val_interval: 500
  num_val_images: 8

diffusion:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  schedule: "linear"
  sampling_timesteps: 250
  ddim_eta: 0.0

augmentation:
  random_flip: true
  random_crop: true
  color_jitter: false

